services:
  postgres:
    image: postgres:16
    container_name: bm-postgres
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - bm_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: bm-redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: bm-api
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"

      DATABASE_URL: "postgresql://book:bookpass@postgres:5432/bookdb?schema=public"
      REDIS_URL: "redis://redis:6379"
      REDIS_TTL: "60"

      JWT_SECRET: "dev_jwt_secret"
      JWT_REFRESH_SECRET: "dev_jwt_refresh_secret"

    volumes:
      - .:/app
      - /app/node_modules

    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  bm_pgdata:
